package Game.Engine.Event;

public enum GameEventType {
    RESOURCE_PRODUCED,
    COLONIST_DAMAGED,
    COLONIST_HUNGRY,
    SCHEDULE_TICKABLE,

    COLONIST_MOVE,

    COLONIST_CASTRAY,
    COLONIST_OBSERVE,

    TILE_NEIGHBOURS

}